-- ============================================
-- STORED PROCEDURES AND FUNCTIONS
-- ============================================

USE flipkart_ecommerce;

-- ============================================
-- PROCEDURE 1: Place Order
-- ============================================

DELIMITER //

DROP PROCEDURE IF EXISTS place_order //

CREATE PROCEDURE place_order(
    IN p_user_id BIGINT,
    IN p_shipping_address_id BIGINT,
    IN p_billing_address_id BIGINT,
    IN p_payment_mode VARCHAR(20),
    IN p_coupon_code VARCHAR(50)
)
BEGIN
    DECLARE v_cart_id BIGINT;
    DECLARE v_subtotal DECIMAL(12, 2);
    DECLARE v_discount DECIMAL(10, 2) DEFAULT 0;
    DECLARE v_membership_discount DECIMAL(10, 2) DEFAULT 0;
    DECLARE v_shipping DECIMAL(10, 2) DEFAULT 50;
    DECLARE v_tax DECIMAL(12, 2);
    DECLARE v_total DECIMAL(12, 2);
    DECLARE v_order_id BIGINT;
    DECLARE v_membership_id BIGINT;
    
    -- Get cart ID
    SELECT cart_id INTO v_cart_id FROM cart WHERE user_id = p_user_id;
    
    -- Calculate subtotal
    SELECT IFNULL(SUM(ci.quantity * ci.price_at_addition), 0) INTO v_subtotal
    FROM cart_items ci
    WHERE ci.cart_id = v_cart_id;
    
    -- Check membership benefits
    SELECT membership_id INTO v_membership_id
    FROM user_membership
    WHERE user_id = p_user_id AND membership_status = 'Active' AND end_date >= CURDATE()
    LIMIT 1;
    
    IF v_membership_id IS NOT NULL THEN
        SELECT mp.discount_percentage INTO v_membership_discount
        FROM user_membership um
        JOIN membership_plans mp ON um.plan_id = mp.plan_id
        WHERE um.membership_id = v_membership_id;
        
        SET v_membership_discount = v_subtotal * (v_membership_discount / 100);
        
        -- Check if free delivery
        SELECT IF(mp.free_delivery = TRUE, 0, 50) INTO v_shipping
        FROM user_membership um
        JOIN membership_plans mp ON um.plan_id = mp.plan_id
        WHERE um.membership_id = v_membership_id;
    END IF;
    
    -- Apply coupon if provided
    IF p_coupon_code IS NOT NULL THEN
        SELECT calculate_order_discount(v_subtotal, p_coupon_code) INTO v_discount;
    END IF;
    
    -- Calculate tax and total
    SET v_tax = (v_subtotal - v_discount - v_membership_discount) * 0.18;
    SET v_total = v_subtotal - v_discount - v_membership_discount + v_tax + v_shipping;
    
    -- Insert order (order_number will be auto-generated by trigger)
    INSERT INTO orders (
        user_id, shipping_address_id, billing_address_id, 
        subtotal_amount, tax_amount, shipping_charges, 
        discount_amount, membership_discount, coupon_code, 
        total_amount, order_status, payment_mode, membership_id
    ) VALUES (
        p_user_id, p_shipping_address_id, p_billing_address_id,
        v_subtotal, v_tax, v_shipping,
        v_discount, v_membership_discount, p_coupon_code,
        v_total, 'Pending', p_payment_mode, v_membership_id
    );
    
    SET v_order_id = LAST_INSERT_ID();
    
    -- Insert order items from cart
    INSERT INTO order_items (order_id, product_id, seller_id, product_name, quantity, unit_price, total_price)
    SELECT v_order_id, p.product_id, p.seller_id, p.product_name, ci.quantity, ci.price_at_addition, 
           ci.quantity * ci.price_at_addition
    FROM cart_items ci
    JOIN products p ON ci.product_id = p.product_id
    WHERE ci.cart_id = v_cart_id;
    
    -- Clear cart
    DELETE FROM cart_items WHERE cart_id = v_cart_id;
    
    -- Update coupon usage
    IF p_coupon_code IS NOT NULL AND v_discount > 0 THEN
        UPDATE coupons SET usage_count = usage_count + 1 WHERE coupon_code = p_coupon_code;
        
        INSERT INTO coupon_usage (coupon_id, user_id, order_id, discount_amount)
        SELECT coupon_id, p_user_id, v_order_id, v_discount
        FROM coupons WHERE coupon_code = p_coupon_code;
    END IF;
    
    SELECT v_order_id AS order_id, v_total AS total_amount;
END //

DELIMITER ;

-- ============================================
-- PROCEDURE 2: Get User Order History with Pagination
-- ============================================

DELIMITER //

DROP PROCEDURE IF EXISTS get_user_orders //

CREATE PROCEDURE get_user_orders(
    IN p_user_id BIGINT,
    IN p_limit INT,
    IN p_offset INT
)
BEGIN
    SELECT 
        o.order_id,
        o.order_number,
        o.total_amount,
        o.order_status,
        o.created_at,
        COUNT(oi.order_item_id) as total_items
    FROM orders o
    LEFT JOIN order_items oi ON o.order_id = oi.order_id
    WHERE o.user_id = p_user_id
    GROUP BY o.order_id
    ORDER BY o.created_at DESC
    LIMIT p_limit OFFSET p_offset;
END //

DELIMITER ;

-- ============================================
-- PROCEDURE 3: Calculate Seller Commission
-- ============================================

DELIMITER //

DROP PROCEDURE IF EXISTS calculate_seller_commission //

CREATE PROCEDURE calculate_seller_commission(
    IN p_seller_id BIGINT,
    IN p_start_date DATE,
    IN p_end_date DATE
)
BEGIN
    SELECT 
        s.seller_id,
        s.business_name,
        s.commission_rate,
        IFNULL(SUM(oi.total_price), 0) as total_sales,
        IFNULL(SUM(oi.total_price * s.commission_rate / 100), 0) as commission_amount
    FROM sellers s
    LEFT JOIN order_items oi ON s.seller_id = oi.seller_id
    LEFT JOIN orders o ON oi.order_id = o.order_id
    WHERE s.seller_id = p_seller_id
    AND (o.order_status = 'Delivered' OR o.order_status IS NULL)
    AND (o.delivered_at BETWEEN p_start_date AND p_end_date OR o.delivered_at IS NULL)
    GROUP BY s.seller_id;
END //

DELIMITER ;

-- ============================================
-- PROCEDURE 4: Update Product Price with History
-- ============================================

DELIMITER //

DROP PROCEDURE IF EXISTS update_product_price //

CREATE PROCEDURE update_product_price(
    IN p_product_id BIGINT,
    IN p_new_selling_price DECIMAL(12, 2)
)
BEGIN
    DECLARE v_old_price DECIMAL(12, 2);
    DECLARE v_discount DECIMAL(5, 2);
    
    SELECT selling_price INTO v_old_price FROM products WHERE product_id = p_product_id;
    
    UPDATE products 
    SET selling_price = p_new_selling_price,
        discount_percentage = ((original_price - p_new_selling_price) / original_price) * 100
    WHERE product_id = p_product_id;
    
    SELECT CONCAT('Price updated from ', v_old_price, ' to ', p_new_selling_price) as message;
END //

DELIMITER ;

-- ============================================
-- PROCEDURE 5: Get Top Selling Products
-- ============================================

DELIMITER //

DROP PROCEDURE IF EXISTS get_top_selling_products //

CREATE PROCEDURE get_top_selling_products(
    IN p_limit INT,
    IN p_category_id BIGINT
)
BEGIN
    IF p_category_id IS NULL THEN
        SELECT 
            p.product_id,
            p.product_name,
            p.brand,
            p.selling_price,
            p.total_sales,
            p.average_rating,
            s.business_name as seller_name
        FROM products p
        JOIN sellers s ON p.seller_id = s.seller_id
        WHERE p.product_status = 'Active'
        ORDER BY p.total_sales DESC
        LIMIT p_limit;
    ELSE
        SELECT 
            p.product_id,
            p.product_name,
            p.brand,
            p.selling_price,
            p.total_sales,
            p.average_rating,
            s.business_name as seller_name
        FROM products p
        JOIN sellers s ON p.seller_id = s.seller_id
        WHERE p.product_status = 'Active'
        AND p.category_id = p_category_id
        ORDER BY p.total_sales DESC
        LIMIT p_limit;
    END IF;
END //

DELIMITER ;

-- ============================================
-- PROCEDURE 6: Process Return Request
-- ============================================

DELIMITER //

DROP PROCEDURE IF EXISTS process_return //

CREATE PROCEDURE process_return(
    IN p_order_item_id BIGINT,
    IN p_return_reason VARCHAR(50),
    IN p_return_description TEXT
)
BEGIN
    DECLARE v_order_id BIGINT;
    DECLARE v_user_id BIGINT;
    DECLARE v_product_id BIGINT;
    DECLARE v_quantity INT;
    DECLARE v_refund_amount DECIMAL(12, 2);
    
    SELECT oi.order_id, o.user_id, oi.product_id, oi.quantity, oi.total_price
    INTO v_order_id, v_user_id, v_product_id, v_quantity, v_refund_amount
    FROM order_items oi
    JOIN orders o ON oi.order_id = o.order_id
    WHERE oi.order_item_id = p_order_item_id;
    
    -- Return number will be auto-generated by trigger
    INSERT INTO returns (
        order_id, order_item_id, user_id, return_reason, 
        return_description, return_quantity, refund_amount, return_status
    ) VALUES (
        v_order_id, p_order_item_id, v_user_id, p_return_reason,
        p_return_description, v_quantity, v_refund_amount, 'Requested'
    );
    
    UPDATE order_items 
    SET item_status = 'Returned'
    WHERE order_item_id = p_order_item_id;
    
    SELECT LAST_INSERT_ID() as return_id;
END //

DELIMITER ;

-- ============================================
-- FUNCTION 1: Calculate User Loyalty Tier
-- ============================================

DELIMITER //

DROP FUNCTION IF EXISTS get_loyalty_tier //

CREATE FUNCTION get_loyalty_tier(p_loyalty_points INT)
RETURNS VARCHAR(20)
DETERMINISTIC
READS SQL DATA
BEGIN
    DECLARE tier VARCHAR(20);
    
    IF p_loyalty_points >= 10000 THEN
        SET tier = 'Platinum';
    ELSEIF p_loyalty_points >= 5000 THEN
        SET tier = 'Gold';
    ELSEIF p_loyalty_points >= 1000 THEN
        SET tier = 'Silver';
    ELSE
        SET tier = 'Bronze';
    END IF;
    
    RETURN tier;
END //

DELIMITER ;

-- ============================================
-- FUNCTION 2: Calculate Delivery Days
-- ============================================

DELIMITER //

DROP FUNCTION IF EXISTS calculate_delivery_days //

CREATE FUNCTION calculate_delivery_days(p_order_id BIGINT)
RETURNS INT
DETERMINISTIC
READS SQL DATA
BEGIN
    DECLARE days INT;
    
    SELECT DATEDIFF(delivered_at, created_at) INTO days
    FROM orders
    WHERE order_id = p_order_id AND order_status = 'Delivered';
    
    RETURN IFNULL(days, 0);
END //

DELIMITER ;

-- ============================================
-- FUNCTION 3: Check Product Stock Availability
-- ============================================

DELIMITER //

DROP FUNCTION IF EXISTS is_product_available //

CREATE FUNCTION is_product_available(p_product_id BIGINT, p_quantity INT)
RETURNS BOOLEAN
DETERMINISTIC
READS SQL DATA
BEGIN
    DECLARE available BOOLEAN;
    DECLARE stock INT;
    
    SELECT stock_quantity INTO stock
    FROM products
    WHERE product_id = p_product_id AND product_status = 'Active';
    
    SET available = (stock >= p_quantity);
    
    RETURN available;
END //

DELIMITER ;

-- ============================================
-- FUNCTION 4: Calculate Order Discount
-- ============================================

DELIMITER //

DROP FUNCTION IF EXISTS calculate_order_discount //

CREATE FUNCTION calculate_order_discount(
    p_subtotal DECIMAL(12, 2),
    p_coupon_code VARCHAR(50)
)
RETURNS DECIMAL(10, 2)
DETERMINISTIC
READS SQL DATA
BEGIN
    DECLARE discount DECIMAL(10, 2) DEFAULT 0;
    DECLARE discount_type VARCHAR(20);
    DECLARE discount_value DECIMAL(10, 2);
    DECLARE max_discount DECIMAL(10, 2);
    
    SELECT c.discount_type, c.discount_value, c.max_discount_amount
    INTO discount_type, discount_value, max_discount
    FROM coupons c
    WHERE c.coupon_code = p_coupon_code
    AND c.is_active = TRUE
    AND NOW() BETWEEN c.start_date AND c.end_date
    AND c.usage_count < c.usage_limit
    LIMIT 1;
    
    IF discount_type = 'Percentage' THEN
        SET discount = p_subtotal * (discount_value / 100);
        IF max_discount IS NOT NULL AND discount > max_discount THEN
            SET discount = max_discount;
        END IF;
    ELSEIF discount_type = 'FixedAmount' THEN
        SET discount = discount_value;
    END IF;
    
    RETURN IFNULL(discount, 0);
END //

DELIMITER ;

-- ============================================
-- FUNCTION 5: Get User Total Spending
-- ============================================

DELIMITER //

DROP FUNCTION IF EXISTS get_user_total_spending //

CREATE FUNCTION get_user_total_spending(p_user_id BIGINT)
RETURNS DECIMAL(12, 2)
DETERMINISTIC
READS SQL DATA
BEGIN
    DECLARE total DECIMAL(12, 2);
    
    SELECT IFNULL(SUM(total_amount), 0) INTO total
    FROM orders
    WHERE user_id = p_user_id AND order_status IN ('Delivered', 'Shipped');
    
    RETURN total;
END //

DELIMITER ;

-- ============================================
-- END OF PROCEDURES AND FUNCTIONS
-- ============================================

